version: '2.2'

services:

# base{{{
  base:
    # image: scratch
    # image: hello-world:latest
    restart: "no"
    build:
      context: ./build/centos
      args:
        EXEC_UID: "${EXEC_UID:-1000}"
        EXEC_USER: "${EXEC_USER:-ansible}"
        EXEC_GID: "${EXEC_GID:-1000}"
        EXEC_GROUP: "${EXEC_GROUP:-ansible}"
    image: localhost:5000/ansible/centos7:latest
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SSH_PATH}:/home/${EXEC_USER}/.ssh:ro
      - ./playbook:/playbook:rw
    extra_hosts:
      - "${TARGET_HOST}:${TARGET_IP_ADDR}"
    working_dir: /playbook
    logging: &logging
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"
# }}}

# vim:set filetype=docker-compose expandtab shiftwidth=2 tabstop=2 foldmethod=marker:
