---
- hosts: all
  become: no
  module_defaults:
    ansible.builtin.setup:
      gather_subset:
        - 'all'
        - '!network'
        - '!hardware'
  gather_facts: yes
  environment: "{{ environment_vars }}"
  pre_tasks:
    - block:
      - name: Test connection
        ping:
      - name: facts
        debug:
          msg: "{{ ansible_facts }}"
      tags: pre_tasks
  roles:
  tasks:
  post_tasks:
